apiVersion: v1
kind: Pod
metadata:
  name: test-do-volumes
spec:
  containers:
  - image: nginx
    name: nginx-demo
    ports:
      - name: web
        containerPort: 80
        protocol: TCP
    volumeMounts:
      - name: html
        mountPath: "/usr/share/nginx/html"
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: pvdo1